version: '3.8'

services:
  gpt-portal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gpt-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  gpt-network:
    driver: bridge